import {
  FilterState,
  KPIData,
  CurvaSData,
  CostDistributionItem,
  StatusObrasItem,
  Project5DDetails,
  TopCompra,
  FluxoCaixaData,
  DesempenhoIndicator,
  Alerta,
  FinanceResultRow,
  FluxoCaixaDetalhadoRow,
  FinanceIndicator,
  FinanceTransaction,
  ComprasCategoriaItem,
  ComprasStatusItem,
  TopFornecedor,
  PedidoAbertoRow,
  ComprasEtapaRow,
  FluxoCaixaMensalData
} from './types';

// Import local images generated by the tool
import escolaRenderImg from './assets/images/escola_render_1782781563699.jpg';
import escolaPlantaImg from './assets/images/escola_planta_1782781575374.jpg';
import escola3DImg from './assets/images/escola_3d_1782781586346.jpg';

// Define static lists for sidebar dropdowns
export const LISTA_OBRAS = [
  'Todas',
  'Escola Municipal Dinâmica',
  'Edifício Residencial Sol',
  'Galpão Logístico Sul'
];

export const LISTA_PERIODOS = [
  'Este Mês',
  'Último Trimestre',
  'Ano de 2025'
];

export const LISTA_CLIENTES = [
  'Todos',
  'Prefeitura Municipal',
  'Sol Empreendimentos',
  'LogiLog Transportes'
];

export const LISTA_RESPONSAVEIS = [
  'Todos',
  'Eng. João Silva',
  'Eng. Maria Santos',
  'Eng. Ricardo Dias'
];

// Project details database
export const OBRAS_DETAILS: Record<string, Project5DDetails> = {
  'Escola Municipal Dinâmica': {
    id: '1',
    name: 'Escola Municipal Dinâmica',
    cliente: 'Prefeitura Municipal',
    tipo: 'Obra Pública',
    contrato: 'Nº 032/2024',
    valorContratado: 24850000,
    prazoContratual: '14/01/2025 a 14/07/2026',
    gerenteObra: 'Eng. João Silva',
    descricaoEscopo: 'Construção de escola com 12 salas, quadra poliesportiva, refeitório e áreas administrativas.',
    quantitativos: [
      { label: 'Área construída', value: '3.200 m²' },
      { label: 'Salas de aula', value: '12' },
      { label: 'Pavimentos', value: '2' },
      { label: 'Estrutural', value: 'Concreto' },
      { label: 'Cobertura', value: 'Metálica' }
    ],
    cronograma: [
      { etapa: 'Serviços Iniciais', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Fundação', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Estrutura', concluido: 65, color: 'bg-amber-500' },
      { etapa: 'Alvenaria', concluido: 40, color: 'bg-amber-500' },
      { etapa: 'Cobertura', concluido: 20, color: 'bg-amber-500' },
      { etapa: 'Instalações', concluido: 10, color: 'bg-amber-500' },
      { etapa: 'Acabamentos', concluido: 0, color: 'bg-slate-700' },
      { etapa: 'Entrega', concluido: 0, color: 'bg-slate-700' }
    ],
    datas: {
      terminoPrevisto: '14/07/2026',
      terminoReprogramado: '28/07/2026',
      atrasoDias: 14
    },
    custosEtapa: [
      { etapa: 'Serviços Iniciais', previsto: 450000, realizado: 430000, desvio: -20000, percentualDesvio: -4.4 },
      { etapa: 'Fundação', previsto: 1280000, realizado: 1250000, desvio: -30000, percentualDesvio: -2.3 },
      { etapa: 'Estrutura', previsto: 5200000, realizado: 5420000, desvio: 220000, percentualDesvio: 4.2 },
      { etapa: 'Alvenaria', previsto: 3150000, realizado: 2970000, desvio: -180000, percentualDesvio: -5.7 },
      { etapa: 'Cobertura', previsto: 2100000, realizado: 2160000, desvio: 60000, percentualDesvio: 2.9 },
      { etapa: 'Instalações', previsto: 4200000, realizado: 1980000, desvio: -2220000, percentualDesvio: -52.9 },
      { etapa: 'Acabamentos', previsto: 5350000, realizado: 0, desvio: -5350000, percentualDesvio: -100.0 },
      { etapa: 'Entrega', previsto: 1200000, realizado: 0, desvio: -1200000, percentualDesvio: -100.0 }
    ]
  },
  'Edifício Residencial Sol': {
    id: '2',
    name: 'Edifício Residencial Sol',
    cliente: 'Sol Empreendimentos',
    tipo: 'Obra Privada',
    contrato: 'Nº 011/2024',
    valorContratado: 58400000,
    prazoContratual: '10/05/2024 a 30/12/2026',
    gerenteObra: 'Eng. Maria Santos',
    descricaoEscopo: 'Torre residencial de alto padrão com 24 andares, subsolo de garagens, área de lazer completa e heliponto.',
    quantitativos: [
      { label: 'Área construída', value: '18.500 m²' },
      { label: 'Apartamentos', value: '96 unidades' },
      { label: 'Pavimentos', value: '24' },
      { label: 'Estrutural', value: 'Concreto Protendido' },
      { label: 'Cobertura', value: 'Laje Impermeabilizada' }
    ],
    cronograma: [
      { etapa: 'Serviços Iniciais', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Fundação', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Estrutura', concluido: 90, color: 'bg-emerald-500' },
      { etapa: 'Alvenaria', concluido: 60, color: 'bg-amber-500' },
      { etapa: 'Cobertura', concluido: 10, color: 'bg-amber-500' },
      { etapa: 'Instalações', concluido: 25, color: 'bg-amber-500' },
      { etapa: 'Acabamentos', concluido: 5, color: 'bg-amber-500' },
      { etapa: 'Entrega', concluido: 0, color: 'bg-slate-700' }
    ],
    datas: {
      terminoPrevisto: '30/12/2026',
      terminoReprogramado: '30/12/2026',
      atrasoDias: 0
    },
    custosEtapa: [
      { etapa: 'Serviços Iniciais', previsto: 1200000, realizado: 1180000, desvio: -20000, percentualDesvio: -1.6 },
      { etapa: 'Fundação', previsto: 3400000, realizado: 3450000, desvio: 50000, percentualDesvio: 1.4 },
      { etapa: 'Estrutura', previsto: 15600000, realizado: 15400000, desvio: -200000, percentualDesvio: -1.2 },
      { etapa: 'Alvenaria', previsto: 8400000, realizado: 8200000, desvio: -200000, percentualDesvio: -2.3 },
      { etapa: 'Cobertura', previsto: 4500000, realizado: 4600000, desvio: 100000, percentualDesvio: 2.2 },
      { etapa: 'Instalações', previsto: 9800000, realizado: 9500000, desvio: -300000, percentualDesvio: -3.0 },
      { etapa: 'Acabamentos', previsto: 12500000, realizado: 450000, desvio: -12050000, percentualDesvio: -96.4 },
      { etapa: 'Entrega', previsto: 3000000, realizado: 0, desvio: -3000000, percentualDesvio: -100.0 }
    ]
  },
  'Galpão Logístico Sul': {
    id: '3',
    name: 'Galpão Logístico Sul',
    cliente: 'LogiLog Transportes',
    tipo: 'Obra Privada',
    contrato: 'Nº 087/2024',
    valorContratado: 65500000,
    prazoContratual: '01/02/2025 a 15/05/2026',
    gerenteObra: 'Eng. Ricardo Dias',
    descricaoEscopo: 'Galpão industrial classe A para logística, com piso de alta resistência, 48 docas e vão livre metálico.',
    quantitativos: [
      { label: 'Área construída', value: '25.000 m²' },
      { label: 'Docas', value: '48' },
      { label: 'Pé-direito', value: '12 metros' },
      { label: 'Estrutural', value: 'Pré-moldado Concreto' },
      { label: 'Cobertura', value: 'Telha Zipada' }
    ],
    cronograma: [
      { etapa: 'Serviços Iniciais', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Fundação', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Estrutura', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Alvenaria', concluido: 100, color: 'bg-emerald-500' },
      { etapa: 'Cobertura', concluido: 95, color: 'bg-emerald-500' },
      { etapa: 'Instalações', concluido: 80, color: 'bg-emerald-500' },
      { etapa: 'Acabamentos', concluido: 50, color: 'bg-amber-500' },
      { etapa: 'Entrega', concluido: 10, color: 'bg-amber-500' }
    ],
    datas: {
      terminoPrevisto: '15/05/2026',
      terminoReprogramado: '10/06/2026',
      atrasoDias: 26
    },
    custosEtapa: [
      { etapa: 'Serviços Iniciais', previsto: 1800000, realizado: 1750000, desvio: -50000, percentualDesvio: -2.7 },
      { etapa: 'Fundação', previsto: 4500000, realizado: 4600000, desvio: 100000, percentualDesvio: 2.2 },
      { etapa: 'Estrutura', previsto: 18200000, realizado: 18500000, desvio: 300000, percentualDesvio: 1.6 },
      { etapa: 'Alvenaria', previsto: 6200000, realizado: 6150000, desvio: -50000, percentualDesvio: -0.8 },
      { etapa: 'Cobertura', previsto: 8800000, realizado: 9200000, desvio: 400000, percentualDesvio: 4.5 },
      { etapa: 'Instalações', previsto: 11000000, realizado: 10800000, desvio: -200000, percentualDesvio: -1.8 },
      { etapa: 'Acabamentos', previsto: 12000000, realizado: 5800000, desvio: -6200000, percentualDesvio: -51.6 },
      { etapa: 'Entrega', previsto: 3000000, realizado: 300000, desvio: -2700000, percentualDesvio: -90.0 }
    ]
  }
};

// Object URLs/Paths mapping
export const VISUAL_ASSETS = {
  render: escolaRenderImg,
  planta: escolaPlantaImg,
  modelo3d: escola3DImg
};

// Main function to get reactive state based on filter parameters
export function getDashboardData(filters: FilterState) {
  // Let's decide which project data to pull
  const selectAllObras = filters.obra === 'Todas';
  const selectedObraName = selectAllObras ? 'Escola Municipal Dinâmica' : filters.obra;
  const projectDetails = OBRAS_DETAILS[selectedObraName] || OBRAS_DETAILS['Escola Municipal Dinâmica'];

  // Adjust numbers dynamically to give realistic visual feel when filtering
  let multiplier = 1.0;
  if (filters.obra === 'Edifício Residencial Sol') multiplier = 1.35;
  if (filters.obra === 'Galpão Logístico Sul') multiplier = 1.62;

  // Let's calculate the values for KPIs
  const kpis: KPIData = {
    receitaContratada: selectAllObras ? 148.75 : parseFloat((projectDetails.valorContratado * 1.25 / 1000000).toFixed(2)),
    custoPrevisto: selectAllObras ? 132.40 : parseFloat((projectDetails.valorContratado / 1000000).toFixed(2)),
    custoReal: selectAllObras ? 121.85 : parseFloat((projectDetails.custosEtapa.reduce((sum, item) => sum + item.realizado, 0) / 1000000).toFixed(2)),
    margemPrevista: selectAllObras ? 10.99 : 14.8,
    margemReal: selectAllObras ? 18.02 : 19.45,
    obrasEmAndamento: selectAllObras ? 8 : 1,
    obrasPublicas: selectAllObras ? 6 : (projectDetails.tipo === 'Obra Pública' ? 1 : 0),
    obrasPrivadas: selectAllObras ? 2 : (projectDetails.tipo === 'Obra Privada' ? 1 : 0),
    avancoMedio: selectAllObras ? 74.5 : Math.round(projectDetails.cronograma.reduce((sum, c) => sum + c.concluido, 0) / projectDetails.cronograma.length),

    // Finance Tab KPIs
    receitaFaturada: selectAllObras ? 8.73 : parseFloat((projectDetails.valorContratado * 0.35 / 1000000).toFixed(2)),
    fluxoCaixaProjetado: selectAllObras ? 2.15 : parseFloat((projectDetails.valorContratado * 0.08 / 1000000).toFixed(2)),
    fluxoCaixaReal: selectAllObras ? 1.87 : parseFloat((projectDetails.valorContratado * 0.075 / 1000000).toFixed(2)),
    desvioOrcamentario: selectAllObras ? -3.8 : -4.2,

    // Compras Tab KPIs
    totalCompradoMes: selectAllObras ? 2.48 : parseFloat((projectDetails.valorContratado * 0.1 / 1000000).toFixed(2)),
    totalCompradoAcumulado: selectAllObras ? 14.21 : parseFloat((projectDetails.valorContratado * 0.57 / 1000000).toFixed(2)),
    economiaObtidaAcumulada: selectAllObras ? 0.78 : parseFloat((projectDetails.valorContratado * 0.03 / 1000000).toFixed(2)),
    percentualEconomia: selectAllObras ? 5.2 : 5.8,
    pedidosEmAberto: selectAllObras ? 19 : 4,
    atrasosEntrega: selectAllObras ? 6 : 1,
    comprasEmergenciais: selectAllObras ? 8 : 2
  };

  // Adjust values based on other filters to make it reactive
  if (filters.periodo === 'Último Trimestre') {
    kpis.receitaContratada = parseFloat((kpis.receitaContratada * 0.8).toFixed(2));
    kpis.custoPrevisto = parseFloat((kpis.custoPrevisto * 0.78).toFixed(2));
    kpis.custoReal = parseFloat((kpis.custoReal * 0.75).toFixed(2));
  } else if (filters.periodo === 'Ano de 2025') {
    kpis.receitaContratada = parseFloat((kpis.receitaContratada * 1.15).toFixed(2));
    kpis.custoPrevisto = parseFloat((kpis.custoPrevisto * 1.12).toFixed(2));
    kpis.custoReal = parseFloat((kpis.custoReal * 1.10).toFixed(2));
  }

  // Curva S Data - Exact replication
  const curvaSData: CurvaSData[] = [
    { mes: 'Jan', previstoFisico: 5.0, realizadoFisico: 5.0, realizadoFinanceiro: 4.8 },
    { mes: 'Fev', previstoFisico: 12.0, realizadoFisico: 13.5, realizadoFinanceiro: 11.5 },
    { mes: 'Mar', previstoFisico: 22.0, realizadoFisico: 24.0, realizadoFinanceiro: 20.0 },
    { mes: 'Abr', previstoFisico: 35.0, realizadoFisico: 37.0, realizadoFinanceiro: 32.5 },
    { mes: 'Mai', previstoFisico: 50.0, realizadoFisico: 52.0, realizadoFinanceiro: 46.0 },
    { mes: 'Jun', previstoFisico: 65.0, realizadoFisico: 64.7, realizadoFinanceiro: 58.2 },
    { mes: 'Jul', previstoFisico: 78.0, realizadoFisico: 0, realizadoFinanceiro: 0 },
    { mes: 'Ago', previstoFisico: 88.0, realizadoFisico: 0, realizadoFinanceiro: 0 },
    { mes: 'Set', previstoFisico: 94.0, realizadoFisico: 0, realizadoFinanceiro: 0 },
    { mes: 'Out', previstoFisico: 98.0, realizadoFisico: 0, realizadoFinanceiro: 0 },
    { mes: 'Nov', previstoFisico: 100.0, realizadoFisico: 0, realizadoFinanceiro: 0 },
    { mes: 'Dez', previstoFisico: 100.0, realizadoFisico: 0, realizadoFinanceiro: 0 }
  ].map(item => {
    if (!selectAllObras) {
      // Modify values based on selected project
      const progress = projectDetails.cronograma.reduce((sum, c) => sum + c.concluido, 0) / projectDetails.cronograma.length;
      return {
        mes: item.mes,
        previstoFisico: Math.min(100, Math.round(item.previstoFisico * (progress / 64.7))),
        realizadoFisico: item.realizadoFisico > 0 ? Math.min(100, Math.round(item.realizadoFisico * (progress / 64.7))) : 0,
        realizadoFinanceiro: item.realizadoFinanceiro > 0 ? Math.min(100, Math.round(item.realizadoFinanceiro * (progress * 0.9 / 58.2))) : 0
      };
    }
    return item;
  });

  // Cost distribution - Doughnut
  const custoDist: CostDistributionItem[] = [
    { name: 'Mão de Obra', value: parseFloat((kpis.custoReal * 0.356).toFixed(2)), percentage: 35.6 },
    { name: 'Materiais', value: parseFloat((kpis.custoReal * 0.412).toFixed(2)), percentage: 41.2 },
    { name: 'Equipamentos', value: parseFloat((kpis.custoReal * 0.087).toFixed(2)), percentage: 8.7 },
    { name: 'Terceiros', value: parseFloat((kpis.custoReal * 0.093).toFixed(2)), percentage: 9.3 },
    { name: 'Outros', value: parseFloat((kpis.custoReal * 0.052).toFixed(2)), percentage: 5.2 }
  ];

  // Status obras
  const statusObras: StatusObrasItem[] = [
    { name: 'No Prazo', count: selectAllObras ? 4 : (projectDetails.datas.atrasoDias === 0 ? 1 : 0), percentage: selectAllObras ? 50 : (projectDetails.datas.atrasoDias === 0 ? 100 : 0), color: '#10b981' },
    { name: 'Atenção', count: selectAllObras ? 3 : (projectDetails.datas.atrasoDias > 0 && projectDetails.datas.atrasoDias <= 15 ? 1 : 0), percentage: selectAllObras ? 37.5 : (projectDetails.datas.atrasoDias > 0 && projectDetails.datas.atrasoDias <= 15 ? 100 : 0), color: '#f59e0b' },
    { name: 'Crítico', count: selectAllObras ? 1 : (projectDetails.datas.atrasoDias > 15 ? 1 : 0), percentage: selectAllObras ? 12.5 : (projectDetails.datas.atrasoDias > 15 ? 100 : 0), color: '#ef4444' }
  ].filter(item => selectAllObras || item.count > 0);

  // Top purchases of the month
  const topCompras: TopCompra[] = [
    { item: 'Aço CA-50', fornecedor: 'Gerdau', valor: 1250000 * multiplier, status: 'Entregue' },
    { item: 'Cimento CPII', fornecedor: 'Votorantim', valor: 820000 * multiplier, status: 'Entregue' },
    { item: 'Blocos Cerâmicos', fornecedor: 'Cerâmica Forte', valor: 415000 * multiplier, status: 'Em Trânsito' },
    { item: 'Telhas Metálicas', fornecedor: 'Tuper', valor: 380000 * multiplier, status: 'Pendente' },
    { item: 'Fios e Cabos', fornecedor: 'Sil', valor: 210000 * multiplier, status: 'Entregue' }
  ];

  // Cash flow accumulated chart
  const fluxoCaixa: FluxoCaixaData[] = [
    { mes: 'Jan', previsto: 1.5, realizado: 1.3 },
    { mes: 'Fev', previsto: 4.2, realizado: 3.9 },
    { mes: 'Mar', previsto: 8.5, realizado: 8.1 },
    { mes: 'Abr', previsto: 14.0, realizado: 13.2 },
    { mes: 'Mai', previsto: 20.2, realizado: 19.5 },
    { mes: 'Jun', previsto: 26.5, realizado: 24.8 },
    { mes: 'Jul', previsto: 33.0, realizado: 0 },
    { mes: 'Ago', previsto: 40.5, realizado: 0 },
    { mes: 'Set', previsto: 47.0, realizado: 0 },
    { mes: 'Out', previsto: 54.2, realizado: 0 },
    { mes: 'Nov', previsto: 61.0, realizado: 0 },
    { mes: 'Dez', previsto: 68.0, realizado: 0 }
  ].map(item => {
    if (!selectAllObras) {
      return {
        mes: item.mes,
        previsto: parseFloat((item.previsto * (projectDetails.valorContratado / 24850000)).toFixed(2)),
        realizado: item.realizado > 0 ? parseFloat((item.realizado * (projectDetails.valorContratado / 24850000)).toFixed(2)) : 0
      };
    }
    return item;
  });

  // Monthly cash flow chart for Finance
  const fluxoCaixaMensal: FluxoCaixaMensalData[] = [
    { mes: 'Jan', projetado: 1.5, realizado: 1.3 },
    { mes: 'Fev', projetado: 2.7, realizado: 2.6 },
    { mes: 'Mar', projetado: 4.3, realizado: 4.2 },
    { mes: 'Abr', projetado: 5.5, realizado: 5.1 },
    { mes: 'Mai', projetado: 6.2, realizado: 6.3 },
    { mes: 'Jun', projetado: 6.3, realizado: 5.3 },
    { mes: 'Jul', projetado: 6.5, realizado: 0 },
    { mes: 'Ago', projetado: 7.5, realizado: 0 },
    { mes: 'Set', projetado: 6.5, realizado: 0 },
    { mes: 'Out', projetado: 7.2, realizado: 0 },
    { mes: 'Nov', projetado: 6.8, realizado: 0 },
    { mes: 'Dez', projetado: 7.0, realizado: 0 }
  ].map(item => {
    if (!selectAllObras) {
      return {
        mes: item.mes,
        projetado: parseFloat((item.projetado * (projectDetails.valorContratado / 24850000)).toFixed(2)),
        realizado: item.realizado > 0 ? parseFloat((item.realizado * (projectDetails.valorContratado / 24850000)).toFixed(2)) : 0
      };
    }
    return item;
  });

  // Performance indicators
  const indicadores: DesempenhoIndicator[] = [
    { name: 'Índice de Produtividade', value: selectAllObras ? 0.82 : 0.88, meta: 1.00, type: 'produtividade' },
    { name: 'Índice de Qualidade', value: selectAllObras ? 0.94 : 0.96, meta: 0.90, type: 'qualidade' },
    { name: 'Índice de Segurança', value: selectAllObras ? 0.91 : 0.95, meta: 0.90, type: 'seguranca' },
    { name: 'Índice de Aderência ao Cronograma', value: selectAllObras ? 0.86 : (projectDetails.datas.atrasoDias > 0 ? 0.81 : 0.94), meta: 0.90, type: 'cronograma' }
  ];

  // Alerts
  const alertas: Alerta[] = ([
    { id: 'a1', text: `Atraso de ${projectDetails.datas.atrasoDias} dias no cronograma da obra ${projectDetails.name}`, severity: (projectDetails.datas.atrasoDias > 15 ? 'critical' : 'warning') as 'critical' | 'warning' },
    { id: 'a2', text: 'Desvio de custo acima de 4% na etapa Estrutura', severity: 'warning' as const },
    { id: 'a3', text: 'Baixo avanço físico na etapa Instalações (10%)', severity: 'warning' as const },
    { id: 'a4', text: '3 solicitações de compras emergenciais em aberto', severity: 'warning' as const }
  ] as Alerta[]).filter(item => {
    if (!selectAllObras) {
      if (item.id === 'a1' && projectDetails.datas.atrasoDias === 0) return false;
    }
    return true;
  });

  // DEMONSTRATIVO DE RESULTADO (ACUMULADO) for Finance Tab
  const financeResults: FinanceResultRow[] = [
    { descricao: 'Receita Contratada', previsto: projectDetails.valorContratado, realizado: projectDetails.valorContratado, desvio: 0, percentualDesvio: 0.0 },
    { descricao: 'Receita Faturada', previsto: projectDetails.valorContratado * 0.38, realizado: projectDetails.valorContratado * 0.351, desvio: -(projectDetails.valorContratado * 0.029), percentualDesvio: -7.6 },
    { descricao: '(-) Custos Diretos', previsto: projectDetails.valorContratado * 0.75, realizado: projectDetails.valorContratado * 0.571, desvio: -(projectDetails.valorContratado * 0.179), percentualDesvio: -23.8 },
    { descricao: '(-) Despesas Indiretas', previsto: projectDetails.valorContratado * 0.054, realizado: projectDetails.valorContratado * 0.048, desvio: -(projectDetails.valorContratado * 0.006), percentualDesvio: -10.4 },
    { descricao: 'Lucro Bruto', previsto: projectDetails.valorContratado * 0.168, realizado: projectDetails.valorContratado * 0.133, desvio: -(projectDetails.valorContratado * 0.035), percentualDesvio: -21.2 },
    { descricao: 'Margem Bruta', previsto: 17.0, realizado: 12.6, desvio: -4.4, percentualDesvio: -4.4 } // Custom handling for margem raw differences
  ];

  // FLUXO DE CAIXA DETALHADO (PRÓXIMOS 6 MESES) for Finance Tab
  const fluxoCaixaDetalhado: FluxoCaixaDetalhadoRow[] = [
    { mes: 'Jun/2025', entradas: 2150000 * multiplier, saidas: 2280000 * multiplier, saldoProjetado: 2020000 * multiplier, saldoReal: 1760000 * multiplier },
    { mes: 'Jul/2025', entradas: 2300000 * multiplier, saidas: 2250000 * multiplier, saldoProjetado: 2070000 * multiplier, saldoReal: 1590000 * multiplier },
    { mes: 'Ago/2025', entradas: 2450000 * multiplier, saidas: 2180000 * multiplier, saldoProjetado: 2340000 * multiplier, saldoReal: 1860000 * multiplier },
    { mes: 'Set/2025', entradas: 2650000 * multiplier, saidas: 2320000 * multiplier, saldoProjetado: 2670000 * multiplier, saldoReal: 2190000 * multiplier },
    { mes: 'Out/2025', entradas: 2700000 * multiplier, saidas: 2400000 * multiplier, saldoProjetado: 2970000 * multiplier, saldoReal: 2480000 * multiplier },
    { mes: 'Nov/2025', entradas: 2800000 * multiplier, saidas: 2500000 * multiplier, saldoProjetado: 3270000 * multiplier, saldoReal: 2790000 * multiplier }
  ];

  // INDICADORES FINANCEIROS for Finance Tab
  const indicadoresFinanceiros: FinanceIndicator[] = [
    { name: 'Índice de Liquidez Corrente', value: selectAllObras ? 1.45 : 1.32, metaLabel: 'meta: > 1,20', status: 'success' },
    { name: 'Índice de Endividamento', value: selectAllObras ? 0.38 : 0.42, metaLabel: 'meta: < 0,60', status: 'success' },
    { name: 'Giro de Estoque (dias)', value: selectAllObras ? 28 : 31, metaLabel: 'meta: < 45', status: 'success' },
    { name: 'Margem Líquida', value: selectAllObras ? 8.6 : 7.9, metaLabel: 'meta: > 8%', status: 'success' },
    { name: 'TIR do Projeto', value: selectAllObras ? 16.2 : 15.1, metaLabel: 'meta: > 12%', status: 'success' }
  ];

  // ÚLTIMAS MOVIMENTAÇÕES for Finance Tab
  const ultimasMovimentacoes: FinanceTransaction[] = [
    { id: 't1', data: '20/05', descricao: 'Recebimento Medição 05', valor: 1250000 * multiplier, tipo: 'entrada' },
    { id: 't2', data: '19/05', descricao: 'Pagamento Fornecedor Gerdau', valor: 420000 * multiplier, tipo: 'saida' },
    { id: 't3', data: '16/05', descricao: 'Pagamento Folha de Obra', valor: 180000 * multiplier, tipo: 'saida' },
    { id: 't4', data: '15/05', descricao: 'Recebimento Medição 04', valor: 1180000 * multiplier, tipo: 'entrada' },
    { id: 't5', data: '12/05', descricao: 'Pagamento Concreto Ltda', valor: 350000 * multiplier, tipo: 'saida' }
  ];

  // Compras por Categoria for Purchasing Tab
  const comprasCategoria: ComprasCategoriaItem[] = [
    { name: 'Aço e Ferragens', value: 14210000 * 0.326 * multiplier, percentage: 32.6 },
    { name: 'Concreto e Cimento', value: 14210000 * 0.234 * multiplier, percentage: 23.4 },
    { name: 'Instalações', value: 14210000 * 0.167 * multiplier, percentage: 16.7 },
    { name: 'Acabamentos', value: 14210000 * 0.148 * multiplier, percentage: 14.8 },
    { name: 'Equipamentos', value: 14210000 * 0.072 * multiplier, percentage: 7.2 },
    { name: 'Outros', value: 14210000 * 0.053 * multiplier, percentage: 5.3 }
  ];

  // Compras por Status for Purchasing Tab
  const comprasStatus: ComprasStatusItem[] = [
    { name: 'Confirmado', value: 3.65 * 0.463 * multiplier, percentage: 46.3 },
    { name: 'Em Aprovação', value: 3.65 * 0.211 * multiplier, percentage: 21.1 },
    { name: 'Aguardando Entrega', value: 3.65 * 0.187 * multiplier, percentage: 18.7 },
    { name: 'Cotação', value: 3.65 * 0.139 * multiplier, percentage: 13.9 }
  ];

  // Top Fornecedores for Purchasing Tab
  const topFornecedores: TopFornecedor[] = [
    { fornecedor: 'Gerdau', comprado: 2350000 * multiplier, participacao: 16.5, economia: 140000 * multiplier, economiaPercentual: 5.6 },
    { fornecedor: 'Votorantim Cimentos', comprado: 1980000 * multiplier, participacao: 14.0, economia: 115000 * multiplier, economiaPercentual: 5.8 },
    { fornecedor: 'Cerâmica Forte', comprado: 1250000 * multiplier, participacao: 8.8, economia: 78000 * multiplier, economiaPercentual: 5.8 },
    { fornecedor: 'Tuper', comprado: 98000 * multiplier, participacao: 6.9, economia: 52000 * multiplier, economiaPercentual: 5.1 },
    { fornecedor: 'Sil Concreto', comprado: 87000 * multiplier, participacao: 6.1, economia: 45000 * multiplier, economiaPercentual: 4.9 },
    { fornecedor: 'Outros', comprado: 7780000 * multiplier, participacao: 54.7, economia: 350000 * multiplier, economiaPercentual: 4.5 }
  ];

  // Pedidos em Aberto for Purchasing Tab
  const pedidosEmAberto: PedidoAbertoRow[] = [
    { pedido: 'PE-0456', data: '20/05/2025', fornecedor: 'Gerdau', categoria: 'Aço e Ferragens', valor: 420000 * multiplier, prevEntrega: '28/05/2025', status: 'Confirmado' },
    { pedido: 'PE-0455', data: '19/05/2025', fornecedor: 'Votorantim Cimentos', categoria: 'Concreto', valor: 310000 * multiplier, prevEntrega: '27/05/2025', status: 'Em Aprovação' },
    { pedido: 'PE-0454', data: '18/05/2025', fornecedor: 'Concreva Forte', categoria: 'Concreto', valor: 285000 * multiplier, prevEntrega: '29/05/2025', status: 'Aguardando Entrega' },
    { pedido: 'PE-0453', data: '17/05/2025', fornecedor: 'Tigre', categoria: 'Instalações', valor: 210000 * multiplier, prevEntrega: '30/05/2025', status: 'Cotação' },
    { pedido: 'PE-0452', data: '16/05/2025', fornecedor: 'Cerâmica Forte', categoria: 'Acabamentos', valor: 195000 * multiplier, prevEntrega: '26/05/2025', status: 'Confirmado' }
  ];

  // Compras por Etapa da Obra for Purchasing Tab
  const comprasEtapa: ComprasEtapaRow[] = [
    { etapa: 'Serviços Iniciais', previsto: 450000, comprado: 430000, executado: 95.6, desvio: -20000, desvioPercentual: -4.4 },
    { etapa: 'Fundação', previsto: 1280000, comprado: 1250000, executado: 97.7, desvio: -30000, desvioPercentual: -2.3 },
    { etapa: 'Estrutura', previsto: 5200000, comprado: 5420000, executado: 104.2, desvio: 220000, desvioPercentual: 4.2 },
    { etapa: 'Alvenaria', previsto: 2650000, comprado: 2320000, executado: 88.0, desvio: 0, desvioPercentual: -8.0 },
    { etapa: 'Cobertura Iniciais', previsto: 870000, comprado: 870000, executado: 100.2, desvio: -9000, desvioPercentual: -0.9 }
  ];

  return {
    filters,
    kpis,
    curvaSData,
    custoDist,
    statusObras,
    topCompras,
    fluxoCaixa,
    fluxoCaixaMensal,
    indicadores,
    alertas,
    projectDetails,
    // Finance
    financeResults,
    fluxoCaixaDetalhado,
    indicadoresFinanceiros,
    ultimasMovimentacoes,
    // Purchasing
    comprasCategoria,
    comprasStatus,
    topFornecedores,
    pedidosEmAberto,
    comprasEtapa
  };
}
